apiVersion: v1
kind: Service
metadata:
  name: my-kafka-app
  namespace: hw4
  labels:
    app: my-kafka-app
spec:
  type: LoadBalancer
  selector:
    app: my-kafka-app
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: web
